const Data = [
	{
		id: 1,
		img: "",
		price: 2096,
		category: "popular",
		title: "Palm Harbor",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
	{
		id: 2,
		img: "",
		price: 2700,
		category: "popular",
		title: "Beverly Springfield",
		adress: "Green Valley, Highland Lake,Fl",
		beds: 4,
		bathrooms: 2,
		area: "6*7",
	},
	{
		id: 3,
		img: "",
		price: 4550,
		category: "popular",
		title: "Faulkner Ave",
		adress: "LA",
		beds: 4,
		bathrooms: 3,
		area: "8*10",
	},
	{
		id: 4,
		img: "",
		price: 2400,
		category: "",
		title: "St. Crystal",
		adress: "210 Green Valley, Highland Lake,Fl",
		beds: 4,
		bathrooms: 2,
		area: "6*8",
	},
	{
		id: 5,
		img: "",
		price: 1500,
		category: "popular",
		title: "The old steele",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
	{
		id: 6,
		img: "",
		price: 2096,
		category: "popular",
		title: "Palm Harbor",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
	{
		id: 7,
		img: "",
		price: 2096,
		category: "popular",
		title: "Palm Harbor",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
	{
		id: 8,
		img: "",
		price: 2096,
		category: "popular",
		title: "Palm Harbor",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
	{
		id: 8,
		img: "",
		price: 2096,
		category: "popular",
		title: "Palm Harbor",
		adress: "2699 Green Valley, Highland Lake,Fl",
		beds: 3,
		bathrooms: 2,
		area: "5*7",
	},
];
export default Data;
