const PropertiesData = [
	{
		id: 0,
		title: "2 BHK House for Sale in GD Colony",
		showPrice: "₹\n97 Lac",
		price: 97,
		img: "images/img0.jpeg",
		area: 1200,
		desc: "Planning to buy an independent house? Have a look at this lavish 2 BHK house available for sale in GD Colony in New Delhi. Facing east, this independent house is on sale. All the documents pertaining to the property are duly approved by the Developer. This ready to move property in GD Colony is available for a competitive price of Rs 97 Lac. A few notable landmarks near the house are red fox hotel, bharti public school. To physically visit this 2 BHK house for sale, you can reach at the given address: GD Colony, New Delhi - East, Delhi NCR.null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 2,
	},
	{
		id: 1,
		title: "3 BHK Builder Floor for Sale in Asha Park, Fateh Nagar",
		showPrice: "₹\n1.45 Cr",
		price: 145,
		img: "images/img1.jpg",
		area: "Ready to Move",
		desc: "Spacious 3BHK Builder Floor with Lift Covered Car Parking. Nearby Market and Park This attractive 3 BHK apartment can be found for sale in Asha Park, Fateh Nagar, New Delhi. This flat all equipped with required facilities, is up for resale. This ready to move flat in Asha Park, Fateh Nagar comes at an affordable price of INR 1.45 Cr. It is semi-furnished to accommodate your needs. jheel park are some major landmarks near the apartment.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 2,
	},
	{
		id: 2,
		title: "4 BHK Builder Floor for Sale in Lajpat Nagar 2",
		showPrice: "₹\n1.70 Cr",
		price: 170,
		img: "images/img2.jpeg",
		area: "1 out of 2",
		desc: "North east facing, this vaastu compliant 4 BHK builder floor is available for sale. Situated in Lajpat Nagar 2, New Delhi, this builder floor is well maintained, though the construction age of the same is above 20 years. Property Specifications This builder floor is semi-furnished and spreads across a carpet area of 1400 sq ft. Blessed with ample natural sunlight and ventilation, this flat is positioned on the 3rd floor of a low raised 5 floor building. This builder floor comprises 4 bedrooms furnished with wardrobes, 3 bathrooms, 2 balconies, a living area, a dining area and a modular kitchen with a piped gas connection and an attached utility area. This flat is beautifully covered with top quality marble flooring that is easy to clean and maintain. Further, the bathrooms are designed in a western and Indian manner, where two are attached and the remaining one is commonly accessible. In addition, the bathrooms are equipped with geysers for instant hot water at any given time. Overlooking the road, the balconies are attached to the drawing room and a bedroom. Facilities This apartment has access to amenities that are necessary, such as open parking spaces, corporation-provided water that is available around-the-clock, 100 power backup, security personnel, and CCTV cameras.Locality Within a distance of 3 km from this property, you will find reputed schools, hospitals, shopping malls, supermarkets, local markets, and many other social amenities. Two metro stations are situated at a distance of 500 meters, whereas the railway station is located at a distance of 10 minutes drive. Various public transport facilities such as taxis, auto rickshaws and buses are easily available here for commuting across the city. For banking needs and services, nationalized banks and ATMs are present in the vicinity.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 1,
	},
	{
		id: 3,
		title: "2 BHK House for Sale in Rohini Sector 16",
		showPrice: "₹\n1.75 Cr",
		price: 175,
		img: "images/img3.jpeg",
		area: "Resale",
		desc: "Golden opportunity for those planning to invest in residential property in New Delhi!! Presenting a spectacular residential building that is now up for sale in Rohini Sector 16. This freehold property is aged between 5-10 years and is spic & span condition thus investing your valuable money & time in this property will surely fetch you great returns in the future.:: :: ::Property Specifications:: :: ::Built across a super area of 2250 sqft, this residential building is vaastu compliant and faces the east-west direction. Basically, the property is spread over the 1st, 2nd, and 3rd floors with roof rights. Moreover, all these floors feature 1 unit of 2 BHK configuration and are accessible via an external staircase.:: :: ::Furthermore, all the units here have a similar configuration comprising 2 bathrooms ( 1 attached, 1 common) and 2 balconies independently connected to 2 bedrooms and overlooking the park. To continue, these units are offered in a furnished condition which includes wardrobes, beds, dining tables, sofas, and electrical fixtures like lights & fans.:: :: ::The kitchen of these units is modular and is loaded with a chimney, cabinets, a granite platform, a sink, and piped gas connection. The bathrooms are of western style and have the provision for installing geysers. The flooring is adorned with Kajaria tiles in all the rooms, which adds grace to the overall decor.:: :: ::Facilities:: :: ::This independent house is supported by facilities like a 24x7 water supply, power backup, and ample open parking space.:: :: ::Locality:: :: ::Situated close to Bansal Bhavan, this property enjoys easy access to essential conveniences. Malls, supermarkets, hospitals, schools, banks, and ATMs lie within a close range of this property. Pubic transport frequently plies to/from this area and the metro station is 700m away whereas Badli Railway Station is at a distance of 1.5km.::null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 2,
	},
	{
		id: 4,
		title: "Owner's 3 BHK Flat for Sale in New India Apartment Rohini Sector 9",
		showPrice: "₹\n1.90 Cr",
		price: 190,
		img: "images/img4.jpeg",
		area: "Unfurnished",
		desc: "3 BHK 100m away from Rohini East metro station and 50m away from District Park. Adjacent is a DDA market where you can get everything be it groceries medicines fast food salons parlors. On the other side adjacent is Delhi International Public School.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 1,
	},
	{
		id: 5,
		title: "2 BHK Builder Floor for Sale in Mohan Garden, Razapur Khurd",
		showPrice: "₹\n26 Lac",
		price: 26,
		img: "images/img5.jpeg",
		area: "East",
		desc: "Up for immediate sale is a 2 BHK apartment in Mohan Garden, Razapur Khurd, New Delhi. Don't miss this bargain flat for sale. This apartment for resale is a great choice. Located in Mohan Garden, Razapur Khurd, this ready to move apartment is sold at a fair selling price of INR 26 Lac. This contemporary apartment is semi-furnished.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 2,
	},
	{
		id: 6,
		title: "Owner's 3 BHK Flat for Sale in DDA Flats Pocket 6 Mayur Vihar 3",
		showPrice: "₹\n1.30 Cr",
		price: 130,
		img: "images/img6.jpeg",
		area: "Garden/Park, Main Road",
		desc: "corner property with 3 car parking new construction Up for immediate sale is a 3 BHK apartment in Mayur Vihar 3, New Delhi. Don't miss this bargain flat for sale. Take the experience of contemporary living to a new high, with exquisitely designed apartments at Dda Flats Pocket 6. This flat all equipped with required facilities, is up for resale. This ready to move flat in Mayur Vihar 3 can be taken at a very economical pricing of INR 1.30 Cr. It is a semi-furnished apartment. red fox hotel are some of the key nearby landmarks.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
	{
		id: 7,
		title: "3 BHK Builder Floor for Sale in Rohini Sector 23",
		showPrice: "₹\n72.5 Lac",
		price: 72.5,
		img: "images/img7.jpeg",
		area: "Power Of Attorney",
		desc: "This residential land for sale has a price breakup of 8 Lac-breakup. This residential land offers the owner the opportunity to construct 3 of floors.null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 1,
	},
	{
		id: 8,
		title: "Owner's Plot for Sale Madanpur Khader Phase 3",
		showPrice: "₹\n8 Lac",
		price: 8,
		img: "images/img8.jpeg",
		area: "1 Open",
		desc: "This residential land for sale has a price breakup of 8 Lac-breakup. This residential land offers the owner the opportunity to construct 3 of floors.null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 1,
	},
	{
		id: 9,
		title: "1 BHK House for Sale in Mayur Vihar 3",
		showPrice: "₹\n55 Lac",
		price: 55,
		img: "images/img9.jpeg",
		area: "2",
		desc: "A very well maintained and semi furnished house located in prime location of Mayur vihar Phase3. The house has 1 bedroom, 1 bathroom, 1 extra small room attached to the living room. The building overlooks garden from both the sides. ::::Situated opposite Ryan International school. Very close proximity to the main bus stand. 200 meter walk for DTC buses, Metro buses, autos, and Erickshaws. The main market of Phase 3 is just 2 mins walk from the house.::::Ample restaurants nearby and is in close proximity to schools such as Salwan public school, St. Marys school and Kerala school.null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 1,
	},
	{
		id: 10,
		title: "Owner's 3 BHK Flat for Sale Mahavir Enclave Part 1",
		showPrice: "₹\n48 Lac",
		price: 48,
		img: "images/img10.jpeg",
		area: "1",
		desc: "Amazing property is avaialble for sale with great and peaceful environment Please contact for more details. Up for immediate sale is a 3 BHK apartment in Mahavir Enclave Part 1, New Delhi. Don't miss this bargain flat for sale. This apartment for resale is a great choice. You can buy this ready to move flat in Mahavir Enclave Part 1 at a reasonable price of INR 48 Lac. This immaculate flat boasts of coming in semi-furnished form which takes the entire deal to the next level. The flat is easily approachable because it is near to dashrathpuri metro station.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
	{
		id: 11,
		title: "5 BHK Builder Floor for Sale in Shakti Nagar",
		showPrice: "₹\n3.75 Cr",
		price: 375,
		img: "images/img11.jpeg",
		area: "156 sqyrd",
		desc: "Designed to provide an ultimate level of comfort and convenience, this gorgeous 5BHK builder floor located in Shakti Nagar, New Delhi is worth investing your time and money. Spacious rooms, modern construction and prime location are few of the notable features of this abode. So, what are you waiting for? Hurry up and grab this deal now!!!::::::Property Specifications::::::With a carpet area of 2400 sqft sqft, this property is situated on the 3rd floor of a 4 storeyed building and is filled with an abundance of fresh air and sunlight, thus promising a pleasant ambience. Facing towards the east direction, this builder floor is elevated in conformity with essential Vastu principles to bring about a sense of peace and harmony among the lives of the residents.::::::Now talking about the layout, this builder floor encompasses 5 bedrooms, living cum dining room (there is a shaft in the living room), modular kitchen, 1 balcony and 5 attached western fashioned bathrooms. Moreover, the marble floorin further creates a great impact on the interiors. The builder floor is well appointed with lights and fans whereas the bedrooms are adorned with wardrobes providing sufficient storage space. ::::::The modular kitchen is well organised with a cooking countertop, sink, piped gas connection, cabinets and chimney to ensure hassle free cooking to the homemaker. Offering unblocked views of the garden and other flats, the balcony linked with the bedroom is perfect for enjoying your cup of tea of coffee.::::::Facilities::::::To ensure more convenience, prime facilities such as one covered parking space and both borewell as well as water supply are available. For quickly accessing all the floors, one lift service is provided. ::::::Locality::::::The well known Chaudhary Sweets is the nearest landmark for this property. A number of leading educational institutions, medical health care centers, shopping malls and supermarkets are present within the vicinity. You can also find noted banks and ATM centers within the vicinity for all your financial services. The metro station and railway station are located at a distance of 2km and 8km respectively while other modes of transport are also easily available for commuting to the rest of the city. null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 1,
	},
	{
		id: 12,
		title: "2 BHK Builder Floor for Sale in Dwaraka More",
		showPrice: "₹\n30 Lac",
		price: 30,
		img: "images/img12.jpeg",
		area: "Ready to Move",
		desc: "Dwaraka More, New Delhi has an attractive 2 BHK Flat for sale. This is one of the best properties available for resale. This ready to move flat in Dwaraka More can be taken at a very economical pricing of INR 30 Lac. The flat is semi-furnished and makes for an ideal choice for any family. The flat is in close proximity to prominent landmarks like jain property.null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 1,
	},
	{
		id: 13,
		title: "2 BHK House for Sale in Nilothi Village, Nilothi",
		showPrice: "₹\n30 Lac",
		price: 30,
		img: "images/img13.jpeg",
		area: "2 out of 3",
		desc: "Those seeking an independent house in New Delhi can invest in this beautiful, available for sale 2 house in Nilothi Village, Nilothi, New Delhi. Known for its strategic location in Nilothi Village, Nilothi, the ready to move independent house can be availed at a price starting from Rs 30 Lac. If you plan to visit this independent 2 BHK house for sale, the address is Nilothi Village, Nilothi, New Delhi - West, Delhi NCR.null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 1,
	},
	{
		id: 14,
		title: "Owner's 2 BHK Flat for Sale in RWA GG1 Block Vikaspuri Vikaspuri",
		showPrice: "₹\n1.25 Cr",
		price: 125,
		img: "images/img14.jpeg",
		area: "Resale",
		desc: "Multistorey apartment is available for sale. It has covered area of 1100 sq-ft, it is a good location property. Please contact for more details. Vikaspuri, New Delhi has an attractive 2 BHK Flat for sale. This flat is situated in the Rwa Gg1 Block Vikaspuri township and is equipped with premium facilities. This flat is an attractive property for resale. The ready to move flat in the prime area of Vikaspuri is available at a reasonable price of INR 1.25 Cr. The flat is unfurnished and makes for an ideal choice for any family.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 2,
	},
	{
		id: 15,
		title: "Owner's 3 BHK Flat for Sale in JVTS Gardens Chhattarpur",
		showPrice: "₹\n45 Lac",
		price: 45,
		img: "images/img15.jpeg",
		area: "Semi-Furnished",
		desc: "Home seekers, a relatively new 3 BHK apartment is available for sale in JVTS Gardens, Chattarpur Extension, New Delhi. Having good connectivity with Chattarpur Metro Station, this property has easy access to essential facilities thus residents here can be assured of living a hassle-free lifestyle. So, without any further delay avail of this offer Property Specifications North facing is this 3 BHK apartment on the 1st floor of a low-rise 4-storey building. This flat occupies a carpet area of 1250 sqft and is thoughtfully crafted to offer comfortable living space for the residents. Bright and airy, this flat is inclusive of 3 bedrooms, 3 western-style bathrooms 2 attached, 1 common, a balcony overlooking the road, a living cum dining area, and a modular kitchen with an attached utility. Extensive woodwork is done in this semi-furnished flat and the flooring is covered with fancy durable ceramic tiles. Facilities Vehicles can be parked at ease in the open parking space available here. The property also benefits from an uninterrupted water supply facility. Locality This property boasts necessary infrastructural facilities like schools, hospitals, malls, and supermarkets within a radius of 1-2km. Leading banks and ATMs are in the vicinity so monetary needs can be fulfilled easily. Commuting wont be a constraint as public transport is widely served tofrom this area.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
	{
		id: 16,
		title: "2 BHK Builder Floor for Sale in Rajpur Khurd Extension, Rajpur",
		showPrice: "₹\n33 Lac",
		price: 33,
		img: "images/img16.jpeg",
		area: "North - West",
		desc: "Looking for a spacious and comfortable home in Rajpur Khurd Extension, New Delhi? Look no further than this 2 BHK builder floor that is now available for sale. Situated in a prime location, this property is perfect for anyone looking to enjoy the convenience of city living while also enjoying the privacy and tranquility of their own home.::::::Property Specifications::::::This beautiful flat boasts a carpet area of 75 square yards, providing ample space for comfortable living. The semi-furnished interior is designed to suit your modern lifestyle, with all the essential amenities readily available. Located on the first floor of a four-story building, this property offers easy access and convenience. The flat is South facing and Vastu compliant, ensuring that you can enjoy a peaceful and harmonious living environment.::::::Designed with perfection, this flat encompasses 2 bedrooms, living cum dining room, modular kitchen with piped gas connection, utility area, 1 balcony and 2 bathrooms. The entire flooring is covered with ceramic and marble flooring which further creates a beautiful impact on the interiors. ::::::Overlooking the main road and surroundings, the balcony connected with the bedroom is perfect for enjoying your cup of tea or coffee. Out of the two bathrooms (1 Indian & 1 western), one is attached to the bedroom and one is common. ::::::Facilities::::::A gym is available within the premises, which is an added advantage for fitness freaks. Key facilities such as covered parking space, borewell & corporation water supply and power backup are available. Also, CCTV cameras have been installed for maximum safety. ::::::Locality::::::Within a range of 1km from this property, you will find some of the major educational institutions, medical health care centers, shopping malls and supermarkets. You can also find banks and ATMs within the vicinity for banking services. The metro station lies within 1.5km while other modes of transport are also readily available, promising great connectivity. null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 1,
	},
	{
		id: 17,
		title: "Owner's 3 BHK Flat for Sale in Arya Apartment Rohini",
		showPrice: "₹\n1.65 Cr",
		price: 165,
		img: "images/img17.jpeg",
		area: "Freehold",
		desc: "3 BHK Builder floor apartment is available for sale. It is a good location property. Please contact for more details. This beautiful 3 BHK Flat is available for sale in Rohini, New Delhi. Take the experience of contemporary living to a new high, with exquisitely designed apartments at Arya Apartment. This flat for resale is just the type of property you have been searching for! This ready to move flat in Rohini is available for a reasonable price of INR 1.65 Cr. The flat is furnished and makes for an ideal choice for any family. Some nearby landmarks are sachdeva junior school.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 2,
	},
	{
		id: 18,
		title: "4 BHK House for Sale in Arjun Garh, Aya Nagar",
		showPrice: "₹\n60 Lac",
		price: 60,
		img: "images/img18.jpeg",
		area: "3",
		desc: "House is open from two sides, 15 ft side lanes and the interesting part is it is near the main road. Wish to buy an independent house in Arjun Garh, Aya Nagar, New Delhi? This lovely 4 BHK house in New Delhi is on sale, and an ideal choice for a family. Placed in the well-connected Arjun Garh, Aya Nagar locality, this ready to move house is being offered at an attractive price tag of Rs 60 Lac. The property boasts of proximity with key landmarks like baba timber. If you wish to visit this individual 4 BHK house for sale, the address is Arjun Garh, Aya Nagar, New Delhi - South, Delhi NCR.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
	{
		id: 19,
		title: "Owner's 1 BHK Flat for Sale Vasant Kunj 2, Vasant Kunj",
		showPrice: "₹\n60 Lac",
		price: 60,
		img: "images/img19.jpeg",
		area: "2",
		desc: "It’s a DDA flat Have a look at this immaculate 1 BHK flat for sale in Vasant Kunj 2, Vasant Kunj, New Delhi. This flat for resale is just the type of property you have been searching for! This ready to move flat in Vasant Kunj 2, Vasant Kunj is available for a reasonable price of INR 60 Lac. The flat is uniquely designed to enhance the living style. It is unfurnished, studded with all the basic facilities.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 2,
	},
	{
		id: 20,
		title: "4 BHK Builder Floor for Sale in Geeta Colony",
		showPrice: "₹\n95 Lac",
		price: 95,
		img: "images/img20.jpeg",
		area: "1400 sqft",
		desc: "Geeta Colony, New Delhi has an attractive 4 BHK Flat for sale. This flat for resale is a choice property. This immaculate flat boasts of coming in semi-furnished form which takes the entire deal to the next level.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 1,
	},
	{
		id: 21,
		title: "3 BHK Builder Floor for Sale in Kirti Nagar",
		showPrice: "₹\n2.75 Cr",
		price: 275,
		img: "images/img21.jpeg",
		area: "Ready to Move",
		desc: "Builder floor apartment is available for sale. It covered area of 200 sq-yrd it is a good location property. Please contact for more details. This beautiful 3 BHK Flat is available for sale in Kirti Nagar, New Delhi. This flat is available as a resale property. This ready to move property in Kirti Nagar is readily available within an affordable cost of INR 2.75 Cr. The flat is sold in furnished condition.null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 1,
	},
	{
		id: 22,
		title: "2 BHK Builder Floor for Sale in Joshi Colony, Patparganj",
		showPrice: "₹\n30 Lac",
		price: 30,
		img: "images/img22.jpeg",
		area: "3 out of 4",
		desc: "Near by metro station govt. Hospital railway station bus adda max hospital 2 BHK flat available for sale in New Delhi in the prime location of Joshi Colony, Patparganj. This flat for resale is the perfect property for you! This ready to move flat in Joshi Colony, Patparganj can be availed at a reasonable price of INR 30 Lac. It is a furnished apartment. moduler kichen double toilet drowing room 2 bedroom. are some major landmarks near the apartment.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
	{
		id: 23,
		title: "Owner's 3 BHK Flat for Sale in DDA Flats Pocket C Ashok Vihar Phase 3",
		showPrice: "₹\n1.80 Cr",
		price: 180,
		img: "images/img23.jpeg",
		area: "Resale",
		desc: "Aged 15 to 20 years, this well maintained 3BHK flat is available for sale. Situated in Sarita Vihar Pocket C, New Delhi, this flat is semi-furnished and is benefited with freehold ownership rights. Therefore, this is an amazing investment opportunity that cannot be missed! ::::::Property Specifications ::::::Spread across a carpet area of 1600 sq ft, this flat on the 1st floor is blessed with ample natural sunlight and ventilation. This flat consists of 3 bedrooms furnished with wardrobes, 3 bathrooms, a balcony, a living area, a dining area, and a modular kitchen with a piped gas ::connection. ::::::Additionally, there is extra space for the 4th bedroom in this flat. The bathrooms are designed in western manner, of which 2 are attached and the third is commonly accessible. Geysers are installed in the bathrooms for instant hot water at any given time. ::::::Overlooking the internal road, the balcony is attached to the living room. Further, this flat is entirely covered with top quality vitrified tile flooring that is easy to clean and maintain. ::::::Facilities ::::::This flat comes with basic facilities such as open parking space, round the clock water ::supply, security guards, and CCTV cameras. ::::::Locality ::::::Well known schools are situated at a distance of 1km whereas Apollo Hospital is located at a very short distance. The market is located nearby, whereas banks and ATMs are situated in the vicinity. ::::::Sarita Vihar Metro Station is located nearby, whereas other public transport facilities, such as taxis, auto rickshaws and buses are easily available here. Also, Sarita Vihar Distruct Park is located adjacent to this property. ::::null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 2,
	},
	{
		id: 24,
		title: "3 BHK Builder Floor for Sale in Vishwakarma Colony, Mehrauli Badarpur Road",
		showPrice: "₹\n55 Lac",
		price: 55,
		img: "images/img24.jpeg",
		area: "Unfurnished",
		desc: "On Road Property, Basement Parking, the metro is outside the colony, the railway station is 3 km away, a gated settlement with Guard, the park is right across from the territory, and Vishal Mega Mart is within the colony.null\n\nRead more",
		beds: 2,
		popular: false,
		bathroom: 1,
	},
	{
		id: 25,
		title: "3 BHK House for Sale in Hari Nagar",
		showPrice: "₹\n2.20 Cr",
		price: 220,
		img: "images/img25.jpeg",
		area: "North - East",
		desc: "Self made building by owner MCD map approved shilder lift. Situated in Hari Nagar, New Delhi, this 3 independent house is up for sale. Smartly situated, this individual house on sale faces south. One should not fret about the house since it has been approved by the Developer. Located in Hari Nagar, the ready to move independent house is available for sale at a reasonable price of Rs 2.20 Cr. The property boasts of proximity with key landmarks like santoshi mata mandir. If you are planning to buy this 3 BHK house on sale, its address is Hari Nagar, New Delhi - West, Delhi NCR.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 2,
	},
	{
		id: 26,
		title: "Owner's 1 BHK Flat for Sale Geeta Colony",
		showPrice: "₹\n30 Lac",
		price: 30,
		img: "images/img26.jpeg",
		area: "Freehold",
		desc: "Up for immediate sale is a 1 BHK apartment in Geeta Colony, New Delhi. Don't miss this bargain flat for sale. This apartment is a property of choice for resale. This ready to move flat in Geeta Colony comes at an affordable price of INR 30 Lac. The flat is available in furnished condition.null\n\nRead more",
		beds: 2,
		popular: true,
		bathroom: 2,
	},
	{
		id: 27,
		title: "3 BHK Builder Floor for Sale in Uttam Nagar East, Uttam Nagar",
		showPrice: "₹\n75 Lac",
		price: 75,
		img: "images/img27.jpeg",
		area: "3",
		desc: "100 Meter from Main Road, Walking distance from Uttam nagar East metro station, MandirGurudwara 2mins away This exquisite 3 BHK Flat is offered for sale in Uttam Nagar East, Uttam Nagar, New Delhi. This flat is an attractive property for resale. The ready to move flat in Uttam Nagar East, Uttam Nagar is all ready for sale at a low-priced budget of INR 75 Lac. The spacious apartment is semi-furnished.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 2,
	},
	{
		id: 28,
		title: "Owner's 3 BHK Flat for Sale in Parvana Vihar Rohini Sector 9",
		showPrice: "₹\n1.85 Cr",
		price: 185,
		img: "images/img28.jpeg",
		area: "3",
		desc: "3 bhk. Discover this immaculate 3 BHK flat for sale at the pristine Rohini Sector 9 in New Delhi. This flat is situated in the Parvana Vihar township and is equipped with premium facilities. Your search ends here, because this flat for resale is among the best bargains in town. This ready to move flat is offered at an economical price of INR 1.85 Cr. The flat is available in semi-furnished condition. The property is constructed with proximity to major landmarks like gd goenka public school.null\n\nRead more",
		beds: 1,
		popular: true,
		bathroom: 1,
	},
	{
		id: 29,
		title: "3 BHK Builder Floor for Sale in Patel Nagar West",
		showPrice: "₹\n1.35 Cr",
		price: 135,
		img: "images/img29.jpeg",
		area: "2250 sqft",
		desc: "spacious Fully furnished 3bhk plus drawing room with all amenities in it. This gorgeous 3 BHK Flat is available for sale in Patel Nagar West, New Delhi. This is a desirable apartment for resale. This ready to move flat in Patel Nagar West is available for a reasonable price of INR 1.35 Cr. This flat is an ideal choice because it is an furnished apartment with all basic amenities.null\n\nRead more",
		beds: 1,
		popular: false,
		bathroom: 1,
	},
];
export default PropertiesData;
